# pvc-test.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-test
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vol
spec:
  replicas: 1
  selector: { matchLabels: { app: nginx-vol } }
  template:
    metadata: { labels: { app: nginx-vol } }
    spec:
      containers:
        - name: web
          image: nginx:stable
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-test
