apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list: []

    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
      database_url: os.environ/DATABASE_URL
      ui_access_mode: admin_only
      default_team_disabled: true

    litellm_settings:
      request_timeout: 600
      drop_params: true
