---
extends: default

ignore: |
  AGENTS.md
  CLAUDE.MD
  docs/**
  kubeconfig/**
  **/*.sealedsecret.yaml

rules:
  document-start: disable
  empty-lines: disable
  line-length:
    max: 300
  truthy:
    allowed-values: ["true", "false", "on"]
