apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: home-lab
  source:
    repoURL: https://github.com/roman-boiko/home-lab-cluster.git
    targetRevision: main
    path: clusters/lab/gitops/platform/authentik-postgres/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true
