apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-db
  namespace: llms
spec:
  instances: 1
  
  bootstrap:
    initdb:
      database: litellm
      owner: litellm
      
  storage:
    size: 10Gi
