---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgCurluzetzV5N9LGTZmAFpEMngSZs7tCDpW2eyF7nLZUD1ANyC3UZp8EkJd56wKiYAhsFbAcPn5Ba4DYXk3BKKyF+txb/QqbzA5MIenwIgSG4BkJzaRd3JMz98XmVzS55eSAA8KHg9Ep1hRx7i3GqURGbv64mpyEcLGLLDr7hIwDjj/fR5bcDSgKZiYrrJu8ph013h4VtGCw09ZpUKeeD3VlmBfLuUFFsWiw9fUZx7+7AaeIYDvg6xCI+yzDpBAuNBGkxz5WikYuWeUhhndc2mU0Hq5N2D8Os9A7eyYUxvydz+KChLjt+8mGAYXYHnXXz6qr2R+EMvVWnzs0ylgsA8zl9hE/E5Jq4Nj8a2YtQZ/ebEshz6CkzNbAF66VlA+vGNFwMIKVTLKkKwotmyiqDBDKU6WqQzh+ltgtQY5pEOLWkdTIDmcmPCtjG7s5377tNvuSYPL5Py9TBgg2ove70CR1G1kLl/YLxAUiK0TtYt01NYCDjT1T0WxxKC7eyxd45nwSpOhLKzAj+Y/BHI0yEYxmdFc8lyamaNFHood2ArWb5QVA3NyUZ7ldw1T4uUkNGpVmMmOhoEHsbj2yUgzDmMlNvEqmU+PoiKEs+JDMVr1aJUvMzMcC21sNKvMNxXuC+TN1QokSQpI2dGx5QJQsuFGW6mPcF/4nfn48DKUeh/Rhgb0BtWJyKjo9tQqSECZ6+wuwGuMH+MIsOdoK4Bm/uiGRr6it4jv9Fw3QpS6g8DrHg==
  template:
    metadata:
      name: datadog-secret
      namespace: datadog
