apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: home-lab-cluster
    site: datadoghq.com
    tags:
      - env:home
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    admissionController:
      enabled: true
    clusterChecks:
      enabled: true
    controlPlaneMonitoring:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
      unbundleEvents: true
    kubeStateMetricsCore:
      enabled: true
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
      scrubProcessArguments: true
    logCollection:
      enabled: true
      containerCollectAll: true
      containerCollectUsingFiles: true
      autoMultiLineDetection: true
    orchestratorExplorer:
      enabled: true
    processDiscovery:
      enabled: true
    prometheusScrape:
      enabled: true
      enableServiceEndpoints: true
    serviceDiscovery:
      enabled: true
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: otel-grpc
          protocol: TCP
        - containerPort: 4318
          hostPort: 4318
          name: otel-http
          protocol: TCP
  override:
    clusterAgent:
      extraConfd:
        configDataMap:
          argocd.yaml: |-
            cluster_check: true
            init_config:
            instances:
              - app_controller_endpoint: http://argocd-metrics.argocd.svc.cluster.local:8082/metrics
                appset_controller_endpoint: http://argocd-applicationset-controller.argocd.svc.cluster.local:8080/metrics
                api_server_endpoint: http://argocd-server-metrics.argocd.svc.cluster.local:8083/metrics
                repo_server_endpoint: http://argocd-repo-server.argocd.svc.cluster.local:8084/metrics
                notifications_controller_endpoint: http://argocd-notifications-controller-metrics.argocd.svc.cluster.local:9001/metrics
                tags:
                  - service:argocd
                  - kube_namespace:argocd
      dnsConfig:
        options:
          - name: ndots
            value: "1"
    nodeAgent:
      containers:
        agent:
          env:
            - name: DD_IGNORE_AUTOCONF
              value: kubernetes_state redisdb
      dnsConfig:
        options:
          - name: ndots
            value: "1"
