apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: home-lab-cluster
    site: datadoghq.com
    tags:
      - env:home
    env:
      - name: DD_ENV
        value: home
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    admissionController:
      enabled: true
    apm:
      enabled: true
      unixDomainSocketConfig:
        enabled: true
    clusterChecks:
      enabled: true
    controlPlaneMonitoring:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
      unbundleEvents: true
    kubeStateMetricsCore:
      enabled: true
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
      scrubProcessArguments: true
    logCollection:
      enabled: true
      containerCollectAll: true
      containerCollectUsingFiles: true
      autoMultiLineDetection: true
    oomKill:
      enabled: true
    orchestratorExplorer:
      enabled: true
    processDiscovery:
      enabled: true
    prometheusScrape:
      enabled: true
      enableServiceEndpoints: true
    serviceDiscovery:
      enabled: true
      networkStats:
        enabled: true
  override:
    nodeAgent:
      volumes:
        - name: system-probe-tmp
          emptyDir: {}
      containers:
        system-probe:
          volumeMounts:
            - name: system-probe-tmp
              mountPath: /var/tmp/datadog-agent
