apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: home-lab-cluster
    site: datadoghq.com
    tags:
      - env:home
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    admissionController:
      enabled: true
    clusterChecks:
      enabled: true
    controlPlaneMonitoring:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
      unbundleEvents: true
    kubeStateMetricsCore:
      enabled: true
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
      scrubProcessArguments: true
    logCollection:
      enabled: true
      containerCollectAll: true
      containerCollectUsingFiles: true
      autoMultiLineDetection: true
    orchestratorExplorer:
      enabled: true
    processDiscovery:
      enabled: true
    prometheusScrape:
      enabled: true
      enableServiceEndpoints: true
    serviceDiscovery:
      enabled: true
      networkStats:
        enabled: true
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: otel-grpc
        - containerPort: 4318
          hostPort: 4318
          name: otel-http
    npm:
      enabled: true
