apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - platform/argocd
  - platform/authentik
  - platform/authentik-postgres
  - platform/cert-manager
  - platform/cilium
  - platform/cloudnative-pg
  - platform/gateway
  - platform/kured
  - platform/litellm
  - platform/longhorn
  - platform/sealed-secrets
  - platform/system-upgrade-controller
