apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - platform/argocd
  - platform/cert-manager
  - platform/cilium
  - platform/gateway
  - platform/longhorn
  - platform/sealed-secrets
