kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "datadog"
spec:
  global:
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    registry: "gcr.io/datadoghq"
    clusterName: "home-lab-cluster"
    tags:
      - "env:home-lab"
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    npm:
      enabled: true
    liveProcessCollection:
      enabled: true
