apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: home-lab
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.11.2
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
          defaultFsType: ext4
          reclaimPolicy: Delete
          volumeBindingMode: WaitForFirstConsumer
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
